### ISSUE TITLE
email spam due to notifications for project reports 

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4094]
**Describe the bug**
Default cron task for notification for intermediate and final is executing every minutes.

**Expected behavior**
A single notification should be sent, so the  crontask should run once a day.

 - mica2 4.3.3

```
DataAccessRequestReportNotificationService.java, ligne 102 :
  @Scheduled(cron = "${dar.reminder.cron:0 0 * * * ?}")
```

**Comment by ymarcon** [comment]
As a workaround, you can specify your own schedule as follow:

```
dar:
  reminder:
    # "<second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>"
    # Current cron set to run every day at mid-night
    cron: "0 0 0 * * ?"
```
