### ISSUE TITLE
Harmonization Project

### ISSUE THREAD

**Issue by kazoompa** [obiba/mica2#4272]
This is a new request from Maelstrom to introduce `Harmonization Initiative` and `Harmonization Protocol`.

`Harmonization Initiative` will replace the current `Harmonization Study`
`Harmonization Protocol` will replace  the current `Harmonized Dateset`

List of tasks:

- [x] Update the current Study taxonomy with a new Vocabulary attribute to:
  -  Identify Individual Study vocabularies
  -  Identify Harmonization Initiative vocabularies
  -  Identify the common vocabularies  
- [x] Update the current Dataset taxonomy with a new Vocabulary attribute to:
  -  Identify Collected Dataset vocabularies
  -  Identify Harmonization Protocol vocabularies
  -  Identify the common vocabularies  
- [x] Upgrade script to update existing taxonomies
   - Add the new attributes described above
- [x] Harmonization Initiative (Harmonization Study)
  - [x] Change Name in translations
  - [x] Add new fields 
    - [x] Start Year
    - [x] End Year 
    - [x]  Additional Information
  - Hide old fields:
    - [x] Harmonization Design
    - [x] Population

- [x] Harmonization Protocol (Harmonized Dataset)
  - [x] Add new fields 
    - [x] Version
    - [x] Information Content
    - [x] Number of Participants
    - [x] Qualitative/Quantitative Effort (is this the full name?)
    - [x] Procedures
    - [x] Infrastructure
    - [x] Additional Information

- [x] Create new Opal Taxonomy for Dataschema Variables:

List of vocabularies:
- Source (can be one or many)
- Informant (can be one or many)
- Time of Collection (can be one or many)
- Wording (can be one or many)
- Measures (can be one or many)
- Procedures (can be one or many)
- Specific Instructions
- Additional Information

(See **Opal Taxonomy for Dataschema Variables** below)

- [x] Dataschema variable
   -  Change the Dataset type title from `Dataschema` => `Core Dataschema`

- [x] UI Modifications
  - Search page has two modes; current study type queries will become implicit, i.e., they would not be shown in the interface. Current `Harmonization Study` query is the mode for Harmonization Initiative mode (mockup will be provided)
    - [x] Change result columns depending on mode
    - [x] Change titles depending on mode
  - Replace all references to the old names (Harmonization Study => Harmonization Initiative, etc)

- [x] Study Specific dataset info:
This item needs to be confirmed but in a nutshell, it will provide more details on how some variables were harmonized, such as the reference variables used etc.

Both or one of these two items can be implemented:
- [x] Add a new vocabulary in a Mlstr taxonomy such as `Mlstr_harmo` as a text field which will contain the required info as a Markdown text.
- [x] Add a new field to the StudyTable of a `Harmonization Protocol` with a more general (Dataset level) information about the specific dataset used during the harmonization process. 
- [x] Manage variable detail page with new "mandatory" taxonomy (`dataschema_requirements` domain)
- [x] `dataschema_requirements` needs to only appear for a harmo query in search?

- [ ] Prepare documentation for users who have already Mica - Initiative / Protocol integration
- [ ] (science) prepare documentation for why we are doing this change (explain new standard)

#### Opal Taxonomy for Dataschema Variables
currently at [maelstrom-taxonomies](https://github.com/maelstrom-research/maelstrom-taxonomies/blob/dev-harmo-project/DataschemaRequirements.yml) (and also in [opal-harmo](https://opal-harmo.maelstrom-research.org/))

```yml
!!org.obiba.opal.core.domain.taxonomy.Taxonomy
"name": "dataschema_requirements"
"title":
  "en": "Dataschema Requirements"
"description": {}
"attributes": {}
"keywords": {}
"vocabularies":
- "name": "targeted_time_period"
  "title":
    "en": "Targeted Time Period"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "source"
  "title":
    "en": "Source"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "informant"
  "title":
    "en": "Informant"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "time_of_collection"
  "title":
    "en": "Time of Collection"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "wording"
  "title":
    "en": "Wording"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "measures"
  "title":
    "en": "Measures"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "procedures"
  "title":
    "en": "Procedures"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "specific_instructions"
  "title":
    "en": "Specific Instructions"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "additional_information"
  "title":
    "en": "Additional Informatiuon"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "rule_category"
  "title":
    "en": "Rule Category"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
- "name": "targeted_entity"
  "title":
    "en": "Targeted Entity"
  "description": {}
  "attributes": {}
  "keywords": {}
  "terms": []
```
