### ISSUE TITLE
feat: configure roles mapping from groups

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#4466]
As requested by @tomkuipers1402

There are 5 default groups in Mica:

mica-administrator
mica-reviewer
mica-editor
mica-data-access-officer
mica-user
Since we are using 2 micas on 1 Agate, we would like to rename these groups to, e.g.,:

mica1-administrator
mica2-administrator
mica1-reviewer
mica2-reviewer
mica1-user
mica2-user
etc.
We would like to do this, to split permissions of a user between the two mica's. I tried by editing the shiro.ini file in /srv/conf/shiro.ini, but the roles are not picked up. Is there a way to do this?

**Comment by ymarcon** [comment]
Added some config statements in mica `application.yml`:

```
# assign roles when user belongs to one or more groups listed
roles:
  mica-administrator: some-administrator-group
  mica-reviewer: some-reviewer-group
  mica-editor: some-editor-group
  mica-data-access-officer: some-data-access-officer-group
  mica-user: some-mica-user-group
```

Default configuration makes feature backward compatible.

Example of having access to mica and being an opal administrator makes a mica administrator:

```
roles:
  mica-administrator: opal-administrator,mica-user
```
